FROM python:3.12-slim AS base

ENV DEBIAN_FRONTEND=noninteractive \
    PATH="/.venv/bin:/root/.cargo/bin:$PATH" \
    UV_COMPILE_BYTECODE=1 \
    UV_PYTHON_DOWNLOADS=never \
    UV_PYTHON=3.12

# dependency setup stage
FROM base AS python-deps

COPY pyproject.toml uv.lock ./

# Install required system tools
RUN set -eux; \
    apt-get update && \
    apt-get -y upgrade && \
    apt-get -y install --no-install-recommends \
        curl \
        ca-certificates

# download uv
RUN pip install uv==0.6.12

# install python dependencies
RUN uv sync --frozen

# runtime stage
FROM base AS runtime

COPY --from=python-deps ./.venv ./.venv

RUN useradd --create-home appuser
WORKDIR /home/appuser
USER appuser

COPY src/ ./src

RUN mkdir logs && touch logs/example.log && \
    python3 -c "import nltk; nltk.download('vader_lexicon')"

CMD ["python3", "-m", "src.app"]
