name: Prod Test - PR

on:
  pull_request:

jobs:
  pytest_build:
    name: Run Pytest & Deploy to coveralls.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          
      - name: Create and populate .coveralls.yml file
        env:
          repo_token: ${{ secrets.repo_token }}
        run: |
          touch .coveralls.yml
          echo repo_token: "$repo_token" >> .coveralls.yml
          mkdir logs
          cat > logs/example.log
        shell: bash

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m nltk.downloader vader_lexicon

      - name: Start Postgres
        run: make start-postgres

      - name: Run tests with pytest
        run: pytest --cov --cov-report xml

      - name: Coveralls
        run: coveralls
      
      - name: Stop Postgres
        run: make stop-postgres